### ISSUE TITLE
Error when starting interaction with math with NVDA

### ISSUE THREAD

**Issue by Neurrone** [NSoiffer/MathCAT#290] opened 2024-10-03 13:34 UTC
* NVDA version: Version: alpha-34198,67f6cb99 (2025.1.0.34198)
* MathCat version: 0.5.6

The following error is logged and math interaction doesn't work:

```
ERROR - external:globalPlugins.MathCAT.MathCAT.MathCATInteraction.script_navigate (21:31:51.082) - MainThread (10464):
integer division or modulo by zero
```

**Comment by NSoiffer** [comment] 2024-10-14 05:36
Sorry for taking a while to respond -- I was busy with some other projects that had deadlines...

I have a newer version that I haven't released yet. Can you try this version:
https://github.com/NSoiffer/MathCATForPython/releases/download/latest/MathCAT-0.6.3.nvda-addon

Download the file and in the NVDA:Tools:Addon Store... dialog, choose "from external source" and point it to the file you just downloaded. If that works, please close the issue.

If that has the same bug, please let me know some more details:
1. What is the expression you are trying to navigate (copy should work once you start navigating -- make sure you are zoomed out all the way.
2. What sequence of keystrokes you used to get to the error message.

Thanks

**Comment by NSoiffer** [comment] 2024-10-25 06:09
Closing due to inaction. Please reopen is this is still an issue.

FYI: [the latest build to try is here](https://drive.google.com/file/d/1nJASo3fX9chaYDIhQUOwzD-C6g5SeRAD/view?usp=drive_link). I hope to get an official release out in less than a week.

**Comment by Neurrone** [comment] 2024-10-25 13:13
Apologies, I missed the previous email. I can still reproduce with 0.6.4 with Firefox 132.

On [this page](https://en.wikipedia.org/wiki/Dijkstra's_algorithm#Proof_of_correctness), the proof of correctness section has some math. Pressing enter is sufficient to trigger the error, and pressing the arrow keys to attempt navigation also triggers it.

**Comment by NSoiffer** [comment] 2024-10-25 22:15
I still can't reproduce the problem. For the correctness of proof section, the only math is "k" and "k+1" . I didn't have any problem with them. In the next section, [Running Time](https://en.wikipedia.org/wiki/Dijkstra's_algorithm#Running_time), there is much more math. I didn't run into a problem with the ones I tried.

Can you tell me:
1. What expression in the document are you having a problem with?
2. What keys are you using to start navigating? What if any keys to you press before hearing the error message?
3. What SpeechStyle setting are you using?
4. What Navigation settings are you using?

For the settings, if you can send me screenshots of the Speech settings pane and the Navigation settings pane, that would be help maybe save you a bunch of typing. Alternatively, send me the contents of  `<user-dir>/AppData/Roaming/MathCAT/prefs.yaml`if  it exists. If it doesn't exist (you haven't set any preferences), that is helpful to know and you don't need to send me your settings because they will be the defaults.

One potential difference is that I'm running 2024.4rc1 and you are running an alpha build. I have the latest sources and ran NVDA from them (essentially an alpha build) and I did not see a problem with them on the 4 or 5 expressions I tried. So it seems unlikely that the version of NVDA is the problem, but maybe something is wrong in your alpha build? That seems highly unlikely though.

I do hear that MathCAT does a sub-optimal jobs where it says "determinant of E" and "determinant of V" instead of "the number of edges" or "the number of vertices". Those it will like never be able to say without author input (possible in the not yet released MathML 4).

**Comment by Neurrone** [comment] 2024-10-26 14:17
That file doesn't exist, all my settings are the defaults.

I've also updated to the latest alpha build, essentially this should be equivalent with running from source.

I'm using the down arrow key till I find the `k+1` expression and pressing enter to interact, and I get this error:

```
ERROR - external:globalPlugins.MathCAT.MathCAT.MathCATInteraction.script_navigate (22:15:57.230) - MainThread (2748):
integer division or modulo by zero
```

I can reproduce this error with all other add-ons disabled except for MathCat and using the Espeak synthesizer.

**Comment by NSoiffer** [comment] 2024-10-27 23:52
Thanks for your persistence. I can now replicate the problem. Surprisingly, the problem is somewhere in the braille generation code.

**Comment by NSoiffer** [comment] 2024-11-14 06:22
Closing as it is now mentioned in the spec.

**Closed by NSoiffer** 2024-11-14 06:22 UTC
