### ISSUE TITLE
Preserve Caps for Math blocks shown in NVDA Speech Viewer

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#189] opened 2023-10-04 09:33 UTC
Example: $STATS&lt;3$
This shows up in NVDA Speech Viewer in lower case. The use case that this hinders is me using the Speech History NVDA add-on to copy a Math block by using its copy most recently spoken text to clipboard feature. The reason why the capitalization was especially important here is because this was one of those probability questions where the set you could draw from explicitly only had capitals so I was almost going to incorrectly answer 0. In general, capitals are really important in Math, and can be the difference between, for instance, a pdf (small f(x)) and cdf (capital F(x)).

**Comment by andrew-l-d** [comment] 2023-10-04 22:37
Apologies if I have missed something - the example is beyond my understanding.  I am also confused about use of the NVDA speech viewer here.  I dropped your example into Word which, for some reason, did not understand the &lt; but the letters were presented in uppercase.  When I dropped it into an HTML page with relevant MathJax letters were in uppercase.  Your example above is also presented with letters in uppercase.
Andrew

**Comment by bhavyashah** [comment] 2023-10-05 02:24
Clarifying via an STR:
* Open NVDA Speech Viewer from NVDA menu> Tools submenu>Speech viewer.
* Navigate to and have NVDA read the Math I included in the ticket body.
* Navigate back to the NVDA Speech Viewer and arrow to the line corresponding to NVDA's speech for the afore mentioned Math block.
Actual Result: The letters show up in lower case in NVDA's Speech Viewer even though NVDA, with MathCAT enabled, actually (correctly) read them as upper case.
Expected Result: Capitalization should be preserved for Math content in NVDA Speech Viewer output.

**Comment by andrew-l-d** [comment] 2023-10-05 05:35
Point taken.  That said, it would not have occurred to me to use the Speech Viewer to read the math content.  It is, after all, primarily intended for sighted developers or for demonstration purposes.  It could be handy for retrieving a long number, as it is not possible to zoom in on long numbers yet in MathCAT (I think it is on Neil's to do list).
NVDA is normally able to show correct case in the Speech Viewer, but maths content seems to be beyond it - doesn't work in MathPlayer either.
Andrew

**Comment by NSoiffer** [comment] 2023-10-22 05:03
When MathCAT speaks a capital letter, it looks at the NVDA settings regarding pitch and beeping for them. It applies those changes and then outputs the lower case letter (in a command to spell it out) to avoid NVDA or the speech engine trying to be clever and doing something themselves with the capital letter.

You can navigate through the letters one by one. You made it "S T A T S", not a single word "STATS", so the navigation works. As @andrew-l-d mentioned, there is an issue for navigating letters and digits in numbers not being implemented yet.

I'm surprised you look to the speech viewer to get more information. I've never heard of anyone doing this. Is it common? Is there something in MathCAT that is missing that causes you to look outside of it for more info?

**Comment by bhavyashah** [comment] 2023-10-24 10:25
I don't directly look at the SPeech Viewer but rather use the Speech History add-on to copy the Math and review it elsewhere. I do this for a few reasons: (a) the phonetic issue, (b) the read current position latency (now fixed), and (c) to somehow copy Math into another document without getting down to the LaTeX code.

**Comment by NSoiffer** [comment] 2023-10-24 19:33
For the copy issue, MathCAT does currently support copying the MathML. I could also put the speech output out as plain text so when you paste into a "dumb" text editor, you get plain text.

If you think that would be useful, please add that as an issue. I think ctrl-c could work for both (MathCAT uses the clipboard "flavor" MathML currently, but could include text. An alternative (harder to do right now but probably not in the future) would be output TeX. If you write up an issue, please include both what you want to happen and how you want to invoke the feature.

**Comment by bhavyashah** [comment] 2023-10-25 09:03
Just to clarify, MathCAT currently supports copying Math through the context menu only, correct? I tried pressing Ctrl+c on a Math block, as well as selecting the Math block with a Shift+right arrow and then Ctrl+c, and nothing happens. Just want to make sure that that is a feature request as opposed to a bug report.
Also, I don't see the "Copy to Clipboard ►  subMenu " documented on https://nsoiffer.github.io/MathCAT/users.html. Is this a feature unrelated to MathCAT? Or is this documented elsewhere?
I may or may not be in sync with you on vocabulary here, so I'll make up my own. To me, there are two formats in which I may want to paste Math: either the LaTeX (the code enclosed by $$), and the plain text of the speech output. Making the paste sensitive to a word processor VS a "dumb" text editor is a fair approach. Another approach would be to allow the user to set a default copy/paste format (and making the other format accessible as a context menu option).
Also, I don't think I can currently copy a paragraph containing a mixture of Math and non-Math at once. Please let me know if this is untrue.
I recognize I'm getting off-topic for this ticket now.

**Comment by NSoiffer** [comment] 2023-10-26 18:55
You need to start navigation for the copy to work -- at that point MathCAT is active and ctrl-c will work. It will say "copy". It will only copy the math as MathML at the moment.

To get text and math to copy, I'd probably have to change NVDA code, not MathCAT code. It's doable, but the issue is an NVDA one.

Write up a separate issue describing in a much detail as you can what you want to happen for math copy. It would be helpful to say what some minimum functionality is and then have a "wish list" for better functionality.

I'll close this one since the original problem is solved.

**Closed by NSoiffer** 2023-10-26 18:55 UTC
